---
- name: update web servers
  hosts: web
  tasks:
  - name: make sure web directory is created
    file:
      path: /home/centos/ram
      state: directory
  - name: ensure file is downloaded
    get_url:
      url: https://filesamples.com/samples/document/txt/sample3.txt
      dest: /home/centos
...
